### ISSUE TITLE
modelrunner compatibility

### ISSUE THREAD

**Issue by chrisnatali** [SEL-Columbia/infrastructure-planning#1]
The way I run networker via modelrunner is by specifying a working directory from which to look for inputs, a json config file (within that working directory, that may reference other files in that dir) and an output directory.  [This is the script that runs it](https://github.com/SEL-Columbia/modelrunner/blob/ffddaa32c5b3dafa45088caa822e75ecb0a0a594/models/networker.sh).  

The json has an associated schema that it can be validated against (and used to generate a form for entering data).  [see here](https://github.com/SEL-Columbia/networker/blob/master/networker/networker_config_schema.json)

I could see how to wrap each tool so it could be run this way.  I propose this method for compatibility with modelrunner, so we could write a script like the following to compute the metrics:

```
input_dir=$1
output_dir=$2

echo "Running estimate electricity cost"
source activate infrastructure-planning
estimate_electricity_cost_by_technology_from_population.py config.json -w $input_dir -o $output_dir
```

**Comment by invisibleroads** [comment]
Chris, I just saw this issue today; thanks for the detailed specs. I'll aim to start and finish the json compatibility by end of day.

Here is a mission document that summarizes upcoming fixes.
https://github.com/SEL-Columbia/infrastructure-planning/blob/2.0.5/missions/InfrastructurePlanning-LocalOverride-20160523-1100.md

**Comment by invisibleroads** [comment]
https://github.com/SEL-Columbia/infrastructure-planning/blob/2.0.5/missions/InfrastructurePlanning-LocalOverride-20160523-1100.md

**Comment by chrisnatali** [comment]
As of v2.0.9, this is not working.  Problem appears to be [here](https://github.com/SEL-Columbia/infrastructure-planning/blob/80c62582f3125a5403a15460b45f382a62460244/estimate_electricity_cost_by_technology_from_population.py#L478)

The ArgumentParser dict is populated with None's when there's nothing specified and the dict merge overwrites what was read from the json config file with those values.  Also, I'm not sure why the json is printed out [here](https://github.com/SEL-Columbia/infrastructure-planning/blob/80c62582f3125a5403a15460b45f382a62460244/estimate_electricity_cost_by_technology_from_population.py#L760)
