### ISSUE TITLE
Levelized cost for technologies not outputted

### ISSUE THREAD

**Issue by shakythesherpa** [SEL-Columbia/infrastructure-planning#6]
My recent run  which is labeled 16 (Electricity Cost by Technology from Population) ran successfully with all nodes being recommended for solar home system(which is an issue in itself as the model seems to be mostly biased towards this technology for most of my runs).  The summary costs output has  zero values for the total levelized cost.

**Comment by shakythesherpa** [comment]
So, i think in this run it seems that the model did not accept my demand override values. I checked this by entering zero values for all categories in the consumption table and hence this outputs all future demand to be zero and hence all costs variables are outputted as zero as well. 
however, it does calculate the total discounted cost (which is suprising) and on this basis assigns the lowest cost technology to the nodes.

**Comment by shakythesherpa** [comment]
I did a test with only a single override column for household demand(maximum_consumption_in_kwh_per_year) and it seems to be ignored.

**Comment by invisibleroads** [comment]
To override household consumption per year, you can use the local override column name `household_consumption_in_kwh_per_year`

Overriding `maximum_consumption_in_kwh_per_year` is equivalent to overriding `projected nodal demand per year` in the old model.
