### ISSUE TITLE
Battery replacement cost included ?

### ISSUE THREAD

**Issue by shakythesherpa** [SEL-Columbia/infrastructure-planning#7]
Is the battery replacement cost which is the major recurring cost for a solar home system included?
Does the input parameter for "Solar Home System Battery Maintenance Labor and Material Cost per Kilowatt-Hour per Year" supposed to include it?

**Comment by shakythesherpa** [comment]
In the reviewing the output costs.csv file in the summary folder, there is a column for solar_home_battery_replacement_lm_cost_per_year reported but this is not shown in the input parameters. How is this incorporated would be good to know.

![image](https://cloud.githubusercontent.com/assets/731717/16429521/3ba6d4d4-3d45-11e6-8803-fa7cba68f1ab.png)

**Comment by invisibleroads** [comment]
The maintenance cost is separate from the replacement cost. The replacement cost is the installation cost divided by the lifetime in years.

### Input

```
solar_home_battery_installation_lm_cost
solar_home_battery_lifetime_in_years
```

### Output

```
solar_home_battery_replacement_lm_cost_per_year =
    solar_home_battery_installation_lm_cost / solar_home_battery_lifetime_in_years
```
