### ISSUE TITLE
Allow users to override unit household level demand per year

### ISSUE THREAD

**Issue by shakythesherpa** [SEL-Columbia/infrastructure-planning#9]
It would be most useful in our case to allow users to override household level demand.
The reason is that lately, most of our TOR ask us to use some sort of poverty data and the way we integrate that into our model is by varying demand across geography based on poverty rates and also whether a place is urban or rural.

FYI, currently there is no variable that refers to unit household demand per year in the glossary.

**Comment by invisibleroads** [comment]
Thanks, Shaky!

You can now override household consumption using the following local override

```
household_consumption_in_kwh_per_year
```
